config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'teachers#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :users, only: %i[show edit update]
  resources :teachers do
    resources :appointments, only: %i[show new create edit update]
  end
  resources :appointments, only: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :teacher
  belongs_to :user
end

app/models/language.rb
class Language < ApplicationRecord
  has_many :teachers, through: :teachers_languages
  validates :name, presence: true
  validates :name, uniqueness: true
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  include PgSearch::Model
  pg_search_scope :global_search,
                  against: %i[name location],
                  associated_against: {
                    languages: [:name]
                  },
                  using: {
                    tsearch: { prefix: true }
                  }
  belongs_to :user

  has_one_attached :photo

  has_many :teachers_languages, dependent: :destroy
  has_many :languages, through: :teachers_languages
  has_many :appointments

  validates :name, presence: true
  validates :location, presence: true
  validates :price, presence: true
  validates :price, numericality: { greater_than: 0 }

  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?
end

app/models/teachers_language.rb
class TeachersLanguage < ApplicationRecord
  belongs_to :teacher
  belongs_to :language
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :teachers
  has_many :appointments
  has_one_attached :photo
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[username email password photo])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: %i[username email password photo])
  end
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  def new
    @appointment = Appointment.new
    @teacher = Teacher.find(params[:teacher_id])
  end

  def create
    @teacher = Teacher.find(params[:teacher_id])
    @appointment = Appointment.new(appointment_params)
    @appointment.user_id = current_user.id
    @appointment.teacher_id = @teacher.id
    @appointment.save
    redirect_to user_path(@appointment.user_id)
  end

  def show
    @appointment = Appointment.find(params[:id])
    @teacher = Teacher.find(@appointment.teacher_id)
  end

  def edit
    @appointment = Appointment.find(params[:id])
    @teacher = Teacher.find(@appointment.teacher_id)
  end

  def update
    @appointment = Appointment.find(params[:id])
    @appointment.update(appointment_params)
    redirect_to user_path(@appointment.user_id)
  end

  def destroy
    @appointment = Appointment.find(params[:id])
    @appointment.destroy
    redirect_to user_path(@appointment.user_id)
  end

  private

  def appointment_params
    params.require(:appointment).permit(:date, :location)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  before_action :set_teacher, only: %i[show edit update destroy]
  skip_before_action :authenticate_user!, only: %i[index show]

  def index
    if params[:query].present?
      sql_query = " \
        teachers.name @@ :query \
        OR teachers.location @@ :query \
        OR languages.name @@ :query \
      "
      @teachers = Teacher.joins(:languages).where(sql_query, query: "%#{params[:query]}%")
                         .uniq
    else
      @teachers = Teacher.all
    end

    @markers = @teachers.map do |teacher|
     {
      lat: teacher.latitude,
      lng: teacher.longitude,
      info_window: render_to_string(partial: "info_window", locals: { teacher: teacher })
     }
    end if @teachers.length != 0
  end

  def new
    @teacher = Teacher.new
  end

  def create
    @user = current_user
    @teacher = Teacher.new(teacher_params)
    @teacher.user = @user
    languages = params[:teacher][:language_ids]
    languages.map! { |l| Language.find(l) }
    @teacher.languages = languages
    if @teacher.save
      redirect_to user_path(@user)
    else
      render :new
    end
  end

  def show
    @appointment = Appointment.new
    @languages = @teacher.languages
  end

  def edit
  end

  def update
    languages = params[:teacher][:language_ids]
    languages.map! { |l| Language.find(l) }
    @teacher.languages = languages
    if @teacher.update(teacher_params)
      redirect_to @teacher.user, notice: 'Teacher was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @teacher.destroy
    redirect_to user_path(@teacher.user), notice: "Teacher was successfully destroyed."
  end


  private

  def set_teacher
    @teacher = Teacher.find(params[:id])
  end

  def teacher_params
    params.require(:teacher).permit(:name, :location, :description, :photo, :price, :user_id, :language_ids)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show]

  def show
    @teachers = @user.teachers
    @appointments = Appointment.where(user_id: current_user.id)
  end

  private

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/appointments/_cards_appointments.html.erb
  <% @appointments.each do |appointment| %>
    <div class="card-product">
      <%= link_to teacher_appointment_path(appointment) do %>
        <%= image_tag (appointment.teacher.photo.attached? ? cl_image_path(appointment.teacher.photo.key) : asset_path("jim.jpg")), class: "avatar-bordered"%>
      <% end %>
      <div class="card-product-infos">
        <div class="card-product-infos-primary">
          <h2><%= appointment.teacher.name %></h2>
          <h3><%= appointment.teacher.price.to_i %> €</h3>
        </div>
        <div class="card-product-infos-secondary">
          <p><%= appointment.teacher.location %></p>
          <p><%= appointment.date %></p>
        </div>
      </div>
      <% if appointment.teacher.user == current_user  %>
        <div class="card-buttons">
          <%= link_to edit_teacher_appointment_path(appointment) do %>
            <i class="fa-solid fa-pen-to-square"></i>
          <% end %>
          <%= link_to appointment_path(appointment), method: :delete, data: { confirm: "Are you sure?" } do %>
            <i class="fa-solid fa-trash"></i>
          <% end %>
        </div>
      <% end %>
    </div>
  <% end %>

app/views/appointments/_form.html.erb
<%= simple_form_for(@appointment) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :start_date, as: :date, html5: true%>
    <%= f.input :location %>
    <%= f.input :language %>
    <%= f.input :price %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/appointments/_form_appointment.html.erb
<%= simple_form_for([@teacher, @appointment]) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :date, as: :date, html5: true%>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/appointments/edit.html.erb
<h1>Editing appointement</h1>

<%= render 'form_appointment', appointment: @appointment %>
<%= link_to 'Back', user_path(@appointment.user) %>

app/views/appointments/new.html.erb
<h1>Add a new appointement</h1>
<%= render 'form_appointment', appointment: @appointment %>

app/views/appointments/show.html.erb
<p><%= @appointment.teacher.name %></p>
<p><%= @appointment.teacher.location %></p>
<p><%= @appointment.teacher.price.to_i %> €</p>
<p><%= @appointment.date %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProjectAirTa</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
 <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
  </head>

  <body>
    <%# Display Navbar %>
    <%= render "shared/navbar" %>
    <%# render "shared/mobilenavbar" %>

    <%# Display routes %>
    <%= yield %>

    <%# Display alertes from Devise %>
    <%= render 'shared/flashes' %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%# Display footer %>
    <%= render "shared/footer" %>

  </body>
</html>

app/views/pages/home.html.erb
<h1>Find me on Pages / home</h1>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
</div>

app/views/shared/_mobilenavbar.html.erb
 <!-- mobile navbar fixed bottom -->
    <footer role="navbar navbar-fixed-bottom" class="mobilenavbarfooter navbar-expand invisible-scrollbar fixed-bottom al-sm-dark-green">
        <div class="container-fluid">
            <div class="navbar-nav justify-content-sm-around align-items-center w-100 h-100">
              <a href="#"><span class="fa-sm mr-sm-2 icon"><i class="fa-solid fa-house"></i></span></a>
              <a href="#"><span class="fa-sm mr-sm-2 icon"><i class="fa fa-user-circle"></i></span></a>
              <a href="#"><span class="fa-sm mr-sm-2 icon"><i class="fa-solid fa-message"></i></span></a>
            </ul>
        </div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag asset_path("LogoAirTA.png") %>
    <% end %>


    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Messages", "#", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag (current_user.photo.attached? ? cl_image_path(current_user.photo.key) : asset_path("emy.jpg")), class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Profile", user_path(current_user), class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
              <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/teachers/_cards_teachers.html.erb
  <% @teachers.each do |teacher| %>
    <div class="card-product">
      <%= link_to teacher_path(teacher) do %>
        <%= image_tag (teacher.photo.attached? ? cl_image_path(teacher.photo.key) : asset_path("jim.jpg")), class: "avatar-bordered"%>
      <% end %>
      <div class="card-product-infos">
        <div class="card-product-infos-primary">
          <h2><%= teacher.name %></h2>
          <h3><%= teacher.appointments.length %> appoints.</h3>
          <p>Mac : <%= teacher.user.username %></p>
        </div>
        <div class="card-product-infos-secondary">
          <p><%= teacher.location %></p>
          <p>
            <% teacher.languages.each do |language| %>
              <%= language.name %>
            <% end %>
          </p>
          <p><%= teacher.price.to_i %> €</p>
        </div>
      </div>
      <% if teacher.user == current_user  %>
        <div class="card-buttons">
          <%= link_to edit_teacher_path(teacher) do %>
            <i class="fa-solid fa-pen-to-square"></i>
          <% end %>
          <%= link_to teacher_path(teacher), method: :delete, data: { confirm: "Are you sure?" } do %>
            <i class="fa-solid fa-trash"></i>
          <% end %>
        </div>
      <% end %>
    </div>
  <% end %>

app/views/teachers/_form.html.erb
<%= simple_form_for(@teacher) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :location %>
    <%= f.association :languages, as: :check_boxes, scope: Language.all, include_hidden: false, include_blank: false, input_html: { multiple: true }%>
    <%= f.input :availability %>
    <%= f.input :price %>
    <%= f.input :photo, as: :file %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/teachers/_form_teachers.html.erb
<%= simple_form_for(@teacher) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :location,
                input_html: { data: { geocoder_target: "location" }, class: "d-none" },
                wrapper_html: { data: { controller: "geocoder", geocoder_api_key_value: ENV['MAPBOX_API_KEY'] } } %>
    <%= f.association :languages, as: :check_boxes, scope: Language.all, include_hidden: false, include_blank: false, input_html: { class: "tag-selector" }, item_wrapper_class: 'tag-item' %>
    <%= f.input :availability %>
    <%= f.input :price %>
    <%= f.input :photo, as: :file %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: "btn-green" %>
  </div>
<% end %>

app/views/teachers/_info_window.html.erb
  <%= link_to teacher_path(teacher) do %>
    <%= image_tag (teacher.photo.attached? ? cl_image_path(teacher.photo.key) : asset_path("jim.jpg")), class: "avatar-bordered"%>
  <% end %>
  <h2><%= teacher.name %></h2>
  <h3><%= teacher.appointments.length %> appoints.</h3>
  <p><%= teacher.location %></p>
  <p>
    <% teacher.languages.each do |language| %>
      <%= language.name %>
    <% end %>
  </p>
  <p><%= teacher.price.to_i %> €</p>

app/views/teachers/edit.html.erb
<div class="container">
  <h1>Editing Teacher</h1>

  <%= render 'form_teachers', teacher: @teacher %>
  <%= link_to 'Show', @teacher %> |
  <%= link_to 'Back', user_path(@teacher.user_id) %>
</div>

app/views/teachers/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%=asset_path("banner.jpg")%>);">
  <div class="container">
    <h1 class="mb-2">Book your TA with <strong>good style </strong><i class="fa-solid fa-thumbs-up"></i></h1>
    <%= form_tag teachers_path, method: :get do %>
    <div class="d-flex">
      <%= text_field_tag :query,
        params[:query],
        class: "form-control",
        placeholder: "Find a super star !"
      %>
      <%= submit_tag "Search", class: "btn btn-primary" %>
    </div>
    <% end %>
  </div>
</div>

<div class="container">
  <div class="main-container">
    <div class="cards cards-on-index">
      <%= render "cards_teachers" %>
    </div>
    <div id="map-on-index" data-controller="mapbox"
      data-mapbox-markers-value="<%= @markers.to_json %>"
      data-mapbox-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
  </div>
</div>

app/views/teachers/new.html.erb
<div class="container">
  <h1>Add a new teacher</h1>
  <%= render 'form_teachers', teacher: @teacher %>
</div>

app/views/teachers/show.html.erb
<div class="show-container">
  <div class="row justify-content-between align-items-center">

    <div class="col-sm-12 col-md-3 col-lg-4">
      <div class="d-flex justify-content-center">
        <div class="photo">
          <%= image_tag (@teacher.photo.attached? ? cl_image_path(@teacher.photo.key) : asset_path("jim.jpg")), class: "img-thumbnail rounded-circle"%>
        </div>
      </div>
    </div>

    <div class="col-sm-12 col-md-3 col-lg-4">
      <div class="details-show d-flex justify-content-between">
        <div class="details-show-left">
          <h1 class="mb-4"><%= @teacher.name.capitalize %> <i class='fa fa-star' style='color: black'> 5</i></h1>
          <p><i class='fas fa-search-location'></i> <%= @teacher.location.capitalize %></p>
          <p><i class='fa fa-language'></i>
            <% @languages.each do |language| %>
              <%= language.name %>
            <% end %>
          <p><i class="fa-solid fa-credit-card"></i> <%= @teacher.price.to_i %>€</p>
          </p>
        </div>
      </div>
    </div>

    <div class="col-sm-12 col-md-3 col-lg-4 shadow-lg p-3 mb-5 bg-body rounded">
      <div class="details-show-right">
        <h2 class="mb-3">Book <%= @teacher.name.capitalize %> with <i class="fa-solid fa-heart"></i></h2>
        <%= simple_form_for([@teacher, @appointment]) do |f| %>
          <%= f.input :date, as: :date, label: false %>
          <%= f.button :submit, "Book a TA", class: "btn-green mt-2" %>
        <% end %>
      </div>
    </div>
  </div>

  <%= link_to 'Back to home', root_path, class:"btn-white mt-4 d-inline-block" %>

</div>

app/views/users/show.html.erb
<div class="container mt-4">
  <div class="info-btn">
    <%= link_to 'Edit my profile', edit_user_registration_path, class:"btn-white mb-3 d-inline-block" %>
    <%= link_to 'Add a teacher', new_teacher_path, class:"btn-green mb-3 d-inline-block" %>
  </div>

  <h1 class="text-center">My profile</h1>
  <% if @teachers.length > 0 %>
  <h2>My <%= @teachers.length %> teachers</h2>
  <% end %>
  <div class="cards">
    <%= render "/teachers/cards_teachers" %>
  </div>

  <h2>My appointments</h2>
  <div class="cards">
    <%= render "/appointments/cards_appointments" %>
  </div>

</div>